#!/bin/sh


if [ -f ~/folio_privates.sh ]
then
  echo Loading folio_privates script
  . ~/folio_privates.sh
fi

echo Configured::
echo $EBSCO_SANDBOX_CLIENT_ID

# jq -r '.name'

echo Testing for presence of JQ

JQTEST=`echo '{  "value":"one" }' | jq -r ".value" | tr -d '\r'`

if [ $JQREST="one" ]
then
  echo JQ installed and working
else
  echo Please install JQ
  exit 1
fi

echo Running

AGREEMENT_TRIAL_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "AgreementType",
  value: "TRIAL",
  label: "Trial"
}
' | jq -r ".id" | tr -d '\r'`

YNO_YES_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "YesNoOther",
  value: "Yes",
  label: "Yes"
}
' | jq -r ".id" | tr -d '\r'`

YNO_NO_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "YesNoOther",
  value: "No",
  label: "No"
}
' | jq -r ".id" | tr -d '\r'`

YNO_OTHER_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "YesNoOther",
  value: "Other",
  label: "Other"
}
' | jq -r ".id" | tr -d '\r'`

STATUS_CURRENT_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "Status",
  value: "Current",
  label: "Current"
}
' | jq -r ".id" | tr -d '\r'`

STATUS_HISTORIC_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "Status",
  value: "Historic",
  label: "Historic"
}
' | jq -r ".id" | tr -d '\r'`

MUST_RENEW_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "RenewalPriority",
  value: "Must",
  label: "Must"
}
' | jq -r ".id" | tr -d '\r'`

NICE_TO_HAVE_RENEW_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "RenewalPriority",
  value: "NiceToHave",
  label: "Nice to Have"
}
' | jq -r ".id" | tr -d '\r'`

AGREEMENT_DRAFT_RDV=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/refdataValues/lookupOrCreate -d '
{
  category: "AgreementType",
  value: "DRAFT",
  label: "Draft"
}
' | jq -r ".id" | tr -d '\r'`

echo Create a trial agreement 

# Create an agreement - Vendor ID generated by uuidgen here, in reality would be fetched from vendor service
TRIAL_AGREEMENT_ID=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/sas -d '
{
  name: "Trial Agreement LR 003",
  description: "This is a trial agreement",
  agreementType: { id: "'"$AGREEMENT_TRIAL_RDV"'" },
  agreementStatus: { id: "'"$STATUS_CURRENT_RDV"'" },
  isPerpetual: { id: "'"$YNO_YES_RDV"'" },
  renewalPriority: { id: "'"$MUST_RENEW_RDV"'" },
  localReference: "TRIAL_ALR_003",
  vendorReference: "TRIAL_AVR_003",
  startDate: "2018-01-01",
  endDate: "2018-12-31",
  renewalDate: "2019-01-01",
  nextReviewDate: "2018-10-01",
  vendor: {
    vendorsUuid: "05f327a6-c4d3-43c2-828f-7d6e7e401c99",
    name:"My Super Vendor",
    sourceURI:"/vendors/some/uri?05f327a6-c4d3-43c2-828f-7d6e7e401c99"
  }
}
' | jq -r ".id" | tr -d '\r'`

echo Create a draft agreement 

# Create an agreement
DRAFT_AGREEMENT_ID=`curl --header "X-Okapi-Tenant: diku" -H "Content-Type: application/json" -X POST http://localhost:8080/erm/sas -d '
{
  name: "Draft Agreement LR 004", 
  description: "This is a draft agreement",
  agreementType: { id: "'"$AGREEMENT_DRAFT_RDV"'" },
  agreementStatus: { id: "'"$STATUS_CURRENT_RDV"'" },
  isPerpetual: { id: "'"$YNO_NO_RDV"'" },
  renewalPriority: { id: "'"$NICE_TO_HAVE_RENEW_RDV"'" },
  localReference: "AGG_LR_004",
  vendorReference: "AGG_VR_004",
  startDate: "2018-01-01"
}
' | jq -r ".id" | tr -d '\r'`
